<a href="https://www.kaggle.com/code/riteshkumarweb/hyperparameter-tunning-using-optuna?scriptVersionId=323997289" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/iabhishekofficial/mobile-price-classification/train.csv
/kaggle/input/datasets/iabhishekofficial/mobile-price-classification/test.csv

In [ ]:
# 📦 Optuna

# Optuna is an Automatic Hyperparameter
# Optimization Framework

# 🎯 Goal:
# Find the best hyperparameters
# automatically

# Instead of manually trying:

# max_depth = 3
# max_depth = 5
# max_depth = 10

# Optuna intelligently searches
# for the best combination


# 🧠 Idea:

# Step 1️⃣
# Define an Objective Function

# Step 2️⃣
# Optuna suggests hyperparameters

# Step 3️⃣
# Train model

# Step 4️⃣
# Evaluate model score

# Step 5️⃣
# Repeat multiple times

# Step 6️⃣
# Return best parameters


# 📦 Important Terms

# Study
# → Complete optimization process

# Trial
# → One experiment with one set
# of hyperparameters

# Objective Function
# → Function returning model score

# Sampler
# → Strategy used to choose
# new hyperparameters


# 📊 Common Hyperparameter Suggestions

# trial.suggest_int()
# → Integer values

# Example:
# max_depth = trial.suggest_int(
#     "max_depth", 2, 20
# )


# trial.suggest_float()
# → Float values

# Example:
# learning_rate = trial.suggest_float(
#     "learning_rate", 0.001, 0.1
# )


# trial.suggest_categorical()
# → Choose from fixed values

# Example:
# kernel = trial.suggest_categorical(
#     "kernel",
#     ["linear", "rbf"]
# )


# trial.suggest_float(log=True)
# → Logarithmic search

# Example:
# C = trial.suggest_float(
#     "C",
#     1e-4,
#     100,
#     log=True
# )


# 📦 Important Parameters

# direction='maximize'
# → Higher score is better

# Example:
# Accuracy
# R² Score

# direction='minimize'
# → Lower score is better

# Example:
# Loss
# RMSE


# n_trials
# → Number of experiments

# Example:
# n_trials = 100

# Optuna tests 100 combinations


# sampler
# → Hyperparameter search strategy

# Example:
# TPESampler()


# study.best_params_
# → Best hyperparameters found


# study.best_value
# → Best score achieved


# study.best_trial
# → Complete best trial details


# 📊 Example Workflow

# Objective Function
#        │
#        ▼
# Trial 1 🎯
#        │
# Trial 2 🎯
#        │
# Trial 3 🎯
#        │
#      ...
#        │
#        ▼
# Best Parameters ✅


# ✅ Advantages

# Faster than GridSearchCV
# Smarter search strategy
# Handles large search spaces
# Automatic optimization
# State-of-the-art tuning tool


# ❌ Disadvantages

# More complex than GridSearchCV
# Results depend on n_trials
# Can be computationally expensive


# 🆚 GridSearchCV vs RandomizedSearchCV vs Optuna

# GridSearchCV
# → Tests ALL combinations
# → Slow but exhaustive

# RandomizedSearchCV
# → Tests RANDOM combinations
# → Faster

# Optuna
# → Learns from previous trials
# → Smarter and usually fastest 🚀

In [3]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

In [4]:
df = pd.read_csv('/kaggle/input/datasets/iabhishekofficial/mobile-price-classification/train.csv')
df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [5]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.3 KB

In [7]:
df['price_range'].value_counts() #Balanced dataset

price_range
1    500
2    500
3    500
0    500
Name: count, dtype: int64

In [8]:
X = df.drop(columns=['price_range'],axis=1)
X

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,842,0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0
2,563,1,0.5,1,2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0
3,615,1,2.5,0,0,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0
4,1821,1,1.2,0,13,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,14,1222,1890,668,13,4,19,1,1,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,3,915,1965,2032,11,10,16,1,1,1
1997,1911,0,0.9,1,1,1,36,0.7,108,8,3,868,1632,3057,9,1,5,1,1,0
1998,1512,0,0.9,0,4,1,46,0.1,145,5,5,336,670,869,18,10,19,1,1,1
1999,510,1,2.0,1,5,1,45,0.9,168,6,16,483,754,3919,19,4,2,1,1,1

In [9]:
y = df['price_range']
y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

# First we try we with Random forest

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

scaler = StandardScaler() #without it we have to LR = max_iter = 1000000 so we scaled the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
rf = RandomForestClassifier(n_estimators=100,max_depth = 8)

In [12]:
rf.fit(X_train_scaled,y_train)
y_pred = rf.predict(X_test_scaled)
score = accuracy_score(y_test,y_pred)
print(f'The accuracy of Logistic Regression is {score*100}%')

cross_val = cross_val_score(rf,X_train_scaled,y_train,cv=5,scoring='accuracy')
print('The cross_val_score of this data is ',cross_val.mean()*100 ,'%')

The accuracy of Logistic Regression is 89.0%
The cross_val_score of this data is  85.9375 %

# Find best parameter using OPTUNA on RandomForestClassifier

In [13]:
import optuna
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score


def objective(trail):
    n_estimators = trail.suggest_int('n_estimator',50,200)
    max_depth = trail.suggest_int('max_depth',3,20)
    model = RandomForestClassifier(n_estimators = n_estimators,max_depth = max_depth,
        random_state = 42  )

    score = cross_val_score(model,X_train_scaled,
                            y_train,
                            cv=5,
                            scoring='accuracy',
                           ).mean()
    return score

In [16]:
study = optuna.create_study(direction='maximize',sampler=optuna.samplers.TPESampler())
study.optimize(objective, n_trials=50)

[I 2026-06-02 17:40:39,981] A new study created in memory with name: no-name-ccc7a8fd-4838-48c8-af0d-77775054e973
[I 2026-06-02 17:40:42,308] Trial 0 finished with value: 0.853125 and parameters: {'n_estimator': 154, 'max_depth': 8}. Best is trial 0 with value: 0.853125.
[I 2026-06-02 17:40:44,402] Trial 1 finished with value: 0.86625 and parameters: {'n_estimator': 117, 'max_depth': 15}. Best is trial 1 with value: 0.86625.
[I 2026-06-02 17:40:45,913] Trial 2 finished with value: 0.85375 and parameters: {'n_estimator': 105, 'max_depth': 7}. Best is trial 1 with value: 0.86625.
[I 2026-06-02 17:40:46,795] Trial 3 finished with value: 0.838125 and parameters: {'n_estimator': 68, 'max_depth': 6}. Best is trial 1 with value: 0.86625.
[I 2026-06-02 17:40:48,164] Trial 4 finished with value: 0.8275 and parameters: {'n_estimator': 116, 'max_depth': 5}. Best is trial 1 with value: 0.86625.
[I 2026-06-02 17:40:50,230] Trial 5 finished with value: 0.8237500000000001 and parameters: {'n_estimator': 191, 'max_depth': 4}. Best is trial 1 with value: 0.86625.
[I 2026-06-02 17:40:51,725] Trial 6 finished with value: 0.8237499999999999 and parameters: {'n_estimator': 140, 'max_depth': 4}. Best is trial 1 with value: 0.86625.
[I 2026-06-02 17:40:54,319] Trial 7 finished with value: 0.87375 and parameters: {'n_estimator': 144, 'max_depth': 19}. Best is trial 7 with value: 0.87375.
[I 2026-06-02 17:40:56,453] Trial 8 finished with value: 0.8706250000000001 and parameters: {'n_estimator': 123, 'max_depth': 11}. Best is trial 7 with value: 0.87375.
[I 2026-06-02 17:40:58,887] Trial 9 finished with value: 0.851875 and parameters: {'n_estimator': 174, 'max_depth': 7}. Best is trial 7 with value: 0.87375.
[I 2026-06-02 17:41:00,359] Trial 10 finished with value: 0.8700000000000001 and parameters: {'n_estimator': 80, 'max_depth': 20}. Best is trial 7 with value: 0.87375.
[I 2026-06-02 17:41:03,036] Trial 11 finished with value: 0.86625 and parameters: {'n_estimator': 150, 'max_depth': 13}. Best is trial 7 with value: 0.87375.
[I 2026-06-02 17:41:04,736] Trial 12 finished with value: 0.869375 and parameters: {'n_estimator': 95, 'max_depth': 18}. Best is trial 7 with value: 0.87375.
[I 2026-06-02 17:41:07,060] Trial 13 finished with value: 0.8706250000000001 and parameters: {'n_estimator': 135, 'max_depth': 11}. Best is trial 7 with value: 0.87375.
[I 2026-06-02 17:41:09,851] Trial 14 finished with value: 0.8706250000000001 and parameters: {'n_estimator': 163, 'max_depth': 11}. Best is trial 7 with value: 0.87375.
[I 2026-06-02 17:41:12,203] Trial 15 finished with value: 0.8706250000000001 and parameters: {'n_estimator': 130, 'max_depth': 16}. Best is trial 7 with value: 0.87375.
[I 2026-06-02 17:41:15,379] Trial 16 finished with value: 0.8631249999999999 and parameters: {'n_estimator': 196, 'max_depth': 9}. Best is trial 7 with value: 0.87375.
[I 2026-06-02 17:41:16,320] Trial 17 finished with value: 0.859375 and parameters: {'n_estimator': 51, 'max_depth': 14}. Best is trial 7 with value: 0.87375.
[I 2026-06-02 17:41:19,423] Trial 18 finished with value: 0.8737499999999999 and parameters: {'n_estimator': 174, 'max_depth': 17}. Best is trial 7 with value: 0.87375.
[I 2026-06-02 17:41:22,690] Trial 19 finished with value: 0.875 and parameters: {'n_estimator': 180, 'max_depth': 20}. Best is trial 19 with value: 0.875.
[I 2026-06-02 17:41:25,990] Trial 20 finished with value: 0.875 and parameters: {'n_estimator': 180, 'max_depth': 20}. Best is trial 19 with value: 0.875.
[I 2026-06-02 17:41:29,237] Trial 21 finished with value: 0.875 and parameters: {'n_estimator': 179, 'max_depth': 20}. Best is trial 19 with value: 0.875.
[I 2026-06-02 17:41:32,473] Trial 22 finished with value: 0.875625 and parameters: {'n_estimator': 178, 'max_depth': 20}. Best is trial 22 with value: 0.875625.
[I 2026-06-02 17:41:36,136] Trial 23 finished with value: 0.874375 and parameters: {'n_estimator': 200, 'max_depth': 18}. Best is trial 22 with value: 0.875625.
[I 2026-06-02 17:41:39,483] Trial 24 finished with value: 0.8768750000000001 and parameters: {'n_estimator': 183, 'max_depth': 20}. Best is trial 24 with value: 0.8768750000000001.
[I 2026-06-02 17:41:42,434] Trial 25 finished with value: 0.8699999999999999 and parameters: {'n_estimator': 162, 'max_depth': 17}. Best is trial 24 with value: 0.8768750000000001.
[I 2026-06-02 17:41:45,883] Trial 26 finished with value: 0.8706250000000001 and parameters: {'n_estimator': 186, 'max_depth': 18}. Best is trial 24 with value: 0.8768750000000001.
[I 2026-06-02 17:41:48,894] Trial 27 finished with value: 0.8712500000000001 and parameters: {'n_estimator': 166, 'max_depth': 16}. Best is trial 24 with value: 0.8768750000000001.
[I 2026-06-02 17:41:52,265] Trial 28 finished with value: 0.87375 and parameters: {'n_estimator': 187, 'max_depth': 19}. Best is trial 24 with value: 0.8768750000000001.
[I 2026-06-02 17:41:55,067] Trial 29 finished with value: 0.8712500000000001 and parameters: {'n_estimator': 156, 'max_depth': 13}. Best is trial 24 with value: 0.8768750000000001.
[I 2026-06-02 17:41:58,240] Trial 30 finished with value: 0.874375 and parameters: {'n_estimator': 171, 'max_depth': 19}. Best is trial 24 with value: 0.8768750000000001.
[I 2026-06-02 17:42:01,595] Trial 31 finished with value: 0.87625 and parameters: {'n_estimator': 186, 'max_depth': 20}. Best is trial 24 with value: 0.8768750000000001.
[I 2026-06-02 17:42:05,005] Trial 32 finished with value: 0.8775000000000001 and parameters: {'n_estimator': 185, 'max_depth': 20}. Best is trial 32 with value: 0.8775000000000001.
[I 2026-06-02 17:42:07,908] Trial 33 finished with value: 0.8700000000000001 and parameters: {'n_estimator': 154, 'max_depth': 17}. Best is trial 32 with value: 0.8775000000000001.
[I 2026-06-02 17:42:11,390] Trial 34 finished with value: 0.87625 and parameters: {'n_estimator': 191, 'max_depth': 19}. Best is trial 32 with value: 0.8775000000000001.
[I 2026-06-02 17:42:15,103] Trial 35 finished with value: 0.8724999999999999 and parameters: {'n_estimator': 200, 'max_depth': 16}. Best is trial 32 with value: 0.8775000000000001.
[I 2026-06-02 17:42:18,626] Trial 36 finished with value: 0.8725000000000002 and parameters: {'n_estimator': 190, 'max_depth': 18}. Best is trial 32 with value: 0.8775000000000001.
[I 2026-06-02 17:42:22,097] Trial 37 finished with value: 0.8712500000000001 and parameters: {'n_estimator': 191, 'max_depth': 15}. Best is trial 32 with value: 0.8775000000000001.
[I 2026-06-02 17:42:25,100] Trial 38 finished with value: 0.8706249999999999 and parameters: {'n_estimator': 166, 'max_depth': 19}. Best is trial 32 with value: 0.8775000000000001.
[I 2026-06-02 17:42:28,136] Trial 39 finished with value: 0.8618750000000001 and parameters: {'n_estimator': 185, 'max_depth': 9}. Best is trial 32 with value: 0.8775000000000001.
[I 2026-06-02 17:42:30,793] Trial 40 finished with value: 0.87375 and parameters: {'n_estimator': 145, 'max_depth': 19}. Best is trial 32 with value: 0.8775000000000001.
[I 2026-06-02 17:42:34,063] Trial 41 finished with value: 0.875 and parameters: {'n_estimator': 179, 'max_depth': 20}. Best is trial 32 with value: 0.8775000000000001.
[I 2026-06-02 17:42:37,674] Trial 42 finished with value: 0.8787499999999999 and parameters: {'n_estimator': 193, 'max_depth': 20}. Best is trial 42 with value: 0.8787499999999999.
[I 2026-06-02 17:42:41,233] Trial 43 finished with value: 0.875625 and parameters: {'n_estimator': 194, 'max_depth': 19}. Best is trial 42 with value: 0.8787499999999999.
[I 2026-06-02 17:42:43,037] Trial 44 finished with value: 0.80625 and parameters: {'n_estimator': 186, 'max_depth': 3}. Best is trial 42 with value: 0.8787499999999999.
[I 2026-06-02 17:42:45,047] Trial 45 finished with value: 0.86875 and parameters: {'n_estimator': 110, 'max_depth': 18}. Best is trial 42 with value: 0.8787499999999999.
[I 2026-06-02 17:42:48,588] Trial 46 finished with value: 0.8774999999999998 and parameters: {'n_estimator': 195, 'max_depth': 19}. Best is trial 42 with value: 0.8787499999999999.
[I 2026-06-02 17:42:51,714] Trial 47 finished with value: 0.8731250000000002 and parameters: {'n_estimator': 170, 'max_depth': 17}. Best is trial 42 with value: 0.8787499999999999.
[I 2026-06-02 17:42:53,404] Trial 48 finished with value: 0.8712499999999999 and parameters: {'n_estimator': 91, 'max_depth': 20}. Best is trial 42 with value: 0.8787499999999999.
[I 2026-06-02 17:42:57,034] Trial 49 finished with value: 0.86875 and parameters: {'n_estimator': 199, 'max_depth': 15}. Best is trial 42 with value: 0.8787499999999999.

In [17]:
study.best_params

{'n_estimator': 193, 'max_depth': 20}

In [18]:
study.best_value

0.8787499999999999

# Visulisation

In [19]:
import optuna

# You can use Matplotlib instead of Plotly for visualization by simply replacing `optuna.visualization` with
# `optuna.visualization.matplotlib` in the following examples.
from optuna.visualization import plot_contour
from optuna.visualization import plot_edf
from optuna.visualization import plot_intermediate_values
from optuna.visualization import plot_optimization_history
from optuna.visualization import plot_parallel_coordinate
from optuna.visualization import plot_param_importances
from optuna.visualization import plot_rank
from optuna.visualization import plot_slice
from optuna.visualization import plot_timeline

In [20]:
plot_optimization_history(study).show()

In [21]:
plot_parallel_coordinate(study)

**See all in the documentation visualization**

# Finding The Best Estimator/model with his best Prameter

In [22]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [23]:
def objective(trial):
    classifier_name = trial.suggest_categorical("classifier", ["SVC", "RandomForestClassifier","GradientBoostingClassifier","LogisticRegression"])
    if classifier_name == "SVC":
       # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])
        
        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)
    elif classifier_name == "RandomForestClassifier":
        ##Random_Forest Parameter 
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])
        
        model = RandomForestClassifier(n_estimators=n_estimators,
                             max_depth=max_depth,
                             min_samples_split=min_samples_split,
                             min_samples_leaf=min_samples_leaf,
                             bootstrap=bootstrap)
        
    elif classifier_name == 'GradientBoostingClassifier':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
        n_estimators=n_estimators,
        learning_rate=learning_rate,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        random_state=42)

    else:
        C = trial.suggest_float('C', 1e-4, 100, log=True)
        penalty = trial.suggest_categorical('penalty', ['l1', 'l2'])
        solver = trial.suggest_categorical('solver', ['liblinear', 'saga'])
        class_weight = trial.suggest_categorical('class_weight',[None, 'balanced'])

        model = LogisticRegression(
        C=C,
        penalty=penalty,
        solver=solver,
        class_weight=class_weight,
        max_iter=1000,
        random_state=42)



    score = cross_val_score(model,X_train_scaled,y_train,cv=5 , scoring='accuracy').mean()
    return score

In [24]:
study=optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=50)

[I 2026-06-02 17:45:49,801] A new study created in memory with name: no-name-8a48c448-128e-4112-a852-4f8084ca16ff
[I 2026-06-02 17:45:51,660] Trial 0 finished with value: 0.840625 and parameters: {'classifier': 'RandomForestClassifier', 'n_estimators': 141, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 0 with value: 0.840625.
[I 2026-06-02 17:45:51,922] Trial 1 finished with value: 0.8799999999999999 and parameters: {'classifier': 'SVC', 'C': 5.716237077434665, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 1 with value: 0.8799999999999999.
[I 2026-06-02 17:45:51,953] Trial 2 finished with value: 0.244375 and parameters: {'classifier': 'LogisticRegression', 'C': 0.00044757935074425735, 'penalty': 'l1', 'solver': 'saga', 'class_weight': None}. Best is trial 1 with value: 0.8799999999999999.
[I 2026-06-02 17:45:56,372] Trial 3 finished with value: 0.8618749999999998 and parameters: {'classifier': 'RandomForestClassifier', 'n_estimators': 275, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 1 with value: 0.8799999999999999.
[I 2026-06-02 17:47:29,326] Trial 4 finished with value: 0.880625 and parameters: {'classifier': 'GradientBoostingClassifier', 'n_estimators': 186, 'learning_rate': 0.03130409340126434, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 4 with value: 0.880625.
[I 2026-06-02 17:47:29,411] Trial 5 finished with value: 0.8418750000000002 and parameters: {'classifier': 'LogisticRegression', 'C': 10.84356948417201, 'penalty': 'l2', 'solver': 'liblinear', 'class_weight': 'balanced'}. Best is trial 4 with value: 0.880625.
[I 2026-06-02 17:47:52,272] Trial 6 finished with value: 0.8625 and parameters: {'classifier': 'GradientBoostingClassifier', 'n_estimators': 54, 'learning_rate': 0.028329689911171855, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 4 with value: 0.880625.
[I 2026-06-02 17:47:52,778] Trial 7 finished with value: 0.7393749999999999 and parameters: {'classifier': 'SVC', 'C': 0.19058212812329126, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 4 with value: 0.880625.
[I 2026-06-02 17:47:57,373] Trial 8 finished with value: 0.85875 and parameters: {'classifier': 'RandomForestClassifier', 'n_estimators': 271, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 4 with value: 0.880625.
[I 2026-06-02 17:47:57,853] Trial 9 finished with value: 0.95875 and parameters: {'classifier': 'LogisticRegression', 'C': 3.456571198935175, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 9 with value: 0.95875.
[I 2026-06-02 17:47:57,946] Trial 10 finished with value: 0.880625 and parameters: {'classifier': 'LogisticRegression', 'C': 0.054699014254172416, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 9 with value: 0.95875.
[I 2026-06-02 17:48:50,119] Trial 11 finished with value: 0.8825 and parameters: {'classifier': 'GradientBoostingClassifier', 'n_estimators': 185, 'learning_rate': 0.1531118466921592, 'max_depth': 19, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 9 with value: 0.95875.
[I 2026-06-02 17:49:16,382] Trial 12 finished with value: 0.883125 and parameters: {'classifier': 'GradientBoostingClassifier', 'n_estimators': 195, 'learning_rate': 0.298066190074451, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 9 with value: 0.95875.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

[I 2026-06-02 17:49:19,815] Trial 13 finished with value: 0.9637500000000001 and parameters: {'classifier': 'LogisticRegression', 'C': 94.03403908937945, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

[I 2026-06-02 17:49:23,243] Trial 14 finished with value: 0.9637500000000001 and parameters: {'classifier': 'LogisticRegression', 'C': 87.12772799090475, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

[I 2026-06-02 17:49:26,698] Trial 15 finished with value: 0.963125 and parameters: {'classifier': 'LogisticRegression', 'C': 70.30370723263073, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

[I 2026-06-02 17:49:30,133] Trial 16 finished with value: 0.963125 and parameters: {'classifier': 'LogisticRegression', 'C': 75.74258337843885, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:30,269] Trial 17 finished with value: 0.8299999999999998 and parameters: {'classifier': 'LogisticRegression', 'C': 0.36821407037808584, 'penalty': 'l1', 'solver': 'liblinear', 'class_weight': 'balanced'}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:30,355] Trial 18 finished with value: 0.7224999999999999 and parameters: {'classifier': 'LogisticRegression', 'C': 0.0040272171692544685, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:31,047] Trial 19 finished with value: 0.960625 and parameters: {'classifier': 'SVC', 'C': 24.89250022003379, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:31,326] Trial 20 finished with value: 0.95375 and parameters: {'classifier': 'LogisticRegression', 'C': 1.6307831858438095, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

[I 2026-06-02 17:49:34,770] Trial 21 finished with value: 0.9637500000000001 and parameters: {'classifier': 'LogisticRegression', 'C': 91.61469436898803, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

[I 2026-06-02 17:49:38,288] Trial 22 finished with value: 0.9637500000000001 and parameters: {'classifier': 'LogisticRegression', 'C': 91.53996589989099, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:39,995] Trial 23 finished with value: 0.95875 and parameters: {'classifier': 'LogisticRegression', 'C': 19.28125488099981, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:40,418] Trial 24 finished with value: 0.849375 and parameters: {'classifier': 'LogisticRegression', 'C': 1.67557526314163, 'penalty': 'l1', 'solver': 'liblinear', 'class_weight': 'balanced'}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:42,373] Trial 25 finished with value: 0.960625 and parameters: {'classifier': 'LogisticRegression', 'C': 26.762649391220677, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:42,459] Trial 26 finished with value: 0.7625000000000001 and parameters: {'classifier': 'LogisticRegression', 'C': 0.00832585505098003, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:43,200] Trial 27 finished with value: 0.78875 and parameters: {'classifier': 'RandomForestClassifier', 'n_estimators': 84, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:43,668] Trial 28 finished with value: 0.74 and parameters: {'classifier': 'SVC', 'C': 42.137631454892755, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:45,641] Trial 29 finished with value: 0.858125 and parameters: {'classifier': 'RandomForestClassifier', 'n_estimators': 126, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:45,795] Trial 30 finished with value: 0.944375 and parameters: {'classifier': 'LogisticRegression', 'C': 0.6296081695722917, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

[I 2026-06-02 17:49:49,233] Trial 31 finished with value: 0.9637500000000001 and parameters: {'classifier': 'LogisticRegression', 'C': 95.57168102786328, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

[I 2026-06-02 17:49:52,657] Trial 32 finished with value: 0.9637500000000001 and parameters: {'classifier': 'LogisticRegression', 'C': 92.24158636544442, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:53,603] Trial 33 finished with value: 0.959375 and parameters: {'classifier': 'LogisticRegression', 'C': 9.265685234971789, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:55,199] Trial 34 finished with value: 0.95875 and parameters: {'classifier': 'LogisticRegression', 'C': 19.559642856229658, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:55,711] Trial 35 finished with value: 0.74 and parameters: {'classifier': 'SVC', 'C': 53.33792046660901, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:56,276] Trial 36 finished with value: 0.96 and parameters: {'classifier': 'LogisticRegression', 'C': 4.48023411659706, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:49:58,374] Trial 37 finished with value: 0.8568749999999999 and parameters: {'classifier': 'LogisticRegression', 'C': 15.742377506743694, 'penalty': 'l1', 'solver': 'liblinear', 'class_weight': 'balanced'}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:50:20,701] Trial 38 finished with value: 0.838125 and parameters: {'classifier': 'GradientBoostingClassifier', 'n_estimators': 236, 'learning_rate': 0.01098988092454669, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:50:24,634] Trial 39 finished with value: 0.8525 and parameters: {'classifier': 'RandomForestClassifier', 'n_estimators': 296, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:50:27,043] Trial 40 finished with value: 0.961875 and parameters: {'classifier': 'LogisticRegression', 'C': 35.90318931350622, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
[I 2026-06-02 17:50:30,176] Trial 41 finished with value: 0.9618749999999998 and parameters: {'classifier': 'LogisticRegression', 'C': 57.961504734281505, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 13 with value: 0.9637500000000001.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

[I 2026-06-02 17:50:33,610] Trial 42 finished with value: 0.9643750000000001 and parameters: {'classifier': 'LogisticRegression', 'C': 98.0983348853976, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 42 with value: 0.9643750000000001.
[I 2026-06-02 17:50:34,486] Trial 43 finished with value: 0.9612499999999999 and parameters: {'classifier': 'LogisticRegression', 'C': 8.460921066381529, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 42 with value: 0.9643750000000001.
[I 2026-06-02 17:50:34,562] Trial 44 finished with value: 0.563125 and parameters: {'classifier': 'LogisticRegression', 'C': 0.00010111954775977372, 'penalty': 'l2', 'solver': 'saga', 'class_weight': None}. Best is trial 42 with value: 0.9643750000000001.
[I 2026-06-02 17:52:00,084] Trial 45 finished with value: 0.8856250000000001 and parameters: {'classifier': 'GradientBoostingClassifier', 'n_estimators': 230, 'learning_rate': 0.0883579768194017, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 7}. Best is trial 42 with value: 0.9643750000000001.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning:

The max_iter was reached which means the coef_ did not converge


In [25]:
study.best_params

{'classifier': 'LogisticRegression',
 'C': 98.0983348853976,
 'penalty': 'l2',
 'solver': 'saga',
 'class_weight': None}

In [26]:
study.best_value

0.9643750000000001

# See Optuna Documentation for more 
https://optuna.readthedocs.io/en/stable/index.html