<a href="https://www.kaggle.com/code/riteshkumarweb/randomforest-classifier-ensemble-learning?scriptVersionId=320080492" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [83]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/organizations/mlg-ulb/creditcardfraud/creditcard.csv
/kaggle/input/datasets/riteshkumarweb/breast-dataset/data.csv

In [ ]:
# 🌲 Random Forest

# Random Forest is an Ensemble Learning algorithm

# It combines multiple Decision Trees
# to make better predictions

# 🎯 Goal:
# Improve accuracy
# Reduce overfitting

# 🧠 Idea:
# "Many trees together perform better
# than one single tree"

# 📦 Random Forest uses:
# ✅ Bagging
# ✅ Random Feature Selection

# Step 1️⃣
# Create multiple random datasets
# using Bootstrap Sampling

# Step 2️⃣
# Train multiple Decision Trees

# Step 3️⃣
# Each tree uses random features
# at every split

# Step 4️⃣
# Combine predictions from all trees


# 🌳 Random Forest Classification

# Used for Classification problems

# Final prediction:
# 🗳️ Majority Voting

# Example:
# Tree1 → Cat 🐱
# Tree2 → Dog 🐶
# Tree3 → Dog 🐶

# Final Prediction:
# Dog 🐶


# 🌲 Random Forest Regression

# Used for Regression problems

# Final prediction:
# 📊 Average of all predictions


# 📦 Important Hyperparameters:

# n_estimators
# → Number of trees in forest

# max_depth
# → Maximum depth of each tree

# max_features
# → Number of random features used per split

# min_samples_split
# → Minimum samples required to split node

# min_samples_leaf
# → Minimum samples required in leaf node


# ✅ Advantages:
# High accuracy
# Reduces overfitting
# Handles non-linear data
# Feature importance available

# ❌ Disadvantages:
# Slower for large forests
# High memory usage
# Harder to interpret


# 📊 Simple Diagram:

#                📥 Original Dataset
#                         │
#       ┌─────────────────┼─────────────────┐
#       │                 │                 │
#   🌳 Tree1          🌳 Tree2          🌳 Tree3
#       │                 │                 │
#      Cat 🐱           Dog 🐶           Dog 🐶
#       └─────────────────┼─────────────────┘
#                         │
#                 🗳️ Majority Voting
#                         │
#                  ✅ Final Prediction

In [84]:
df = pd.read_csv('/kaggle/input/datasets/riteshkumarweb/breast-dataset/data.csv')

In [85]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
df['diagnosis'] = enc.fit_transform(df['diagnosis'])

In [86]:
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,1,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,1,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,1,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,1,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,0,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [87]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [88]:
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [89]:
df['diagnosis'].value_counts() #This is imblanced dataset

diagnosis
0    357
1    212
Name: count, dtype: int64

In [90]:
X = df.iloc[:,1:]
X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [91]:
y =df.iloc[:,0]
y

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64

# Accuracy and Cross_val_score with Logisitic Regression

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model1 = LogisticRegression(max_iter = 10000,class_weight='balanced')
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)
score =  accuracy_score(y_test,y_pred1)

from sklearn. model_selection import cross_val_score
print(np.mean(cross_val_score(model1,X,y,cv=10,scoring='accuracy')))

0.9525689223057643

# Accuracy and cross_val_score with  Bagging classifier

In [110]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier 
bag = BaggingClassifier(estimator=DecisionTreeClassifier(),bootstrap=True)
bag.fit(X_train,y_train)
y_pred2 = bag.predict(X_test)
score =  accuracy_score(y_test,y_pred2)
from sklearn. model_selection import cross_val_score
print(np.mean(cross_val_score(bag ,X,y,cv=10,scoring='accuracy')))

0.9526002506265664

# Accuracy and cross_val_score with Random Forest

In [111]:
from sklearn.ensemble import RandomForestClassifier

# Create the model
model_d = RandomForestClassifier(max_features = 'sqrt', random_state=42)

model_d.fit(X_train,y_train)
y_pred3 = model_d.predict(X_test)
score =  accuracy_score(y_test,y_pred3)
print(score)
from sklearn. model_selection import cross_val_score
print(np.mean(cross_val_score(model_d,X,y,cv=10,scoring='accuracy')))
#Here is hightest Accuracy

0.9649122807017544
0.9631578947368421

# HyperParameter Tunning of Random Forest with GridSearchCV

In [112]:
n_estimators = [20,60,100,120]
max_features = [0.2,0.6,1.0, None]
max_depth = [2,8,None]
max_samples = [0.5,0.75,1.0]
bootstrap= [True,False] 
criterion = ['gini', 'entropy', 'log_loss']
from sklearn.model_selection import GridSearchCV
rm = RandomForestClassifier()
search = GridSearchCV(estimator=rm,param_grid=params,scoring='accuracy',cv=10 ,n_jobs = -1)
search.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
4320 fits failed out of a total of 8640.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
4320 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py", line 431, in fit
    raise ValueError(
ValueError: `max_sample` cannot be set if `bootstrap=False`. Either switch to `bootstrap=True` or set `max_sample=None`.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [0.92971014 0.95599034 0.94285024 0.94057971 0.94280193 0.94280193
 0.94280193 0.94280193 0.94502415 0.94497585 0.94497585 0.94497585
 0.94724638 0.95376812 0.94724638 0.95164251 0.94507246 0.95376812
 0.94942029 0.95381643 0.94285024 0.9494686  0.94942029 0.95381643
 0.94289855 0.9494686  0.94289855 0.94516908 0.93202899 0.93855072
 0.9494686  0.94942029 0.93850242 0.947343   0.94512077 0.94289855
 0.94724638 0.94942029 0.94729469 0.94951691 0.94077295 0.94729469
 0.94067633 0.94719807 0.93845411 0.9494686  0.94729469 0.94729469
 0.95594203 0.96478261 0.9515942  0.96487923 0.94942029 0.95599034
 0.9647343  0.96478261 0.9647343  0.96033816 0.95821256 0.96478261
 0.95381643 0.95169082 0.962657   0.96700483 0.95376812 0.96270531
 0.962657   0.96922705 0.95376812 0.9647343  0.95821256 0.95821256
 0.96033816 0.96700483 0.95608696 0.96043478 0.95613527 0.962657
 0.96705314 0.96270531 0.95826087 0.9626087  0.96038647 0.962657
 0.95608696 0.95821256 0.96483092 0.96483092 0.95164251 0.95816425
 0.95826087 0.96270531 0.95381643 0.96917874 0.95826087 0.962657
 0.95164251 0.95816425 0.95594203 0.95816425 0.95821256 0.95821256
 0.96043478 0.96700483 0.96256039 0.96043478 0.96700483 0.96478261
 0.95391304 0.96922705 0.96043478 0.96483092 0.95821256 0.9626087
 0.96478261 0.962657   0.95608696 0.96043478 0.96922705 0.962657
 0.95391304 0.95826087 0.9605314  0.95826087 0.9605314  0.962657
 0.95613527 0.95830918 0.96038647 0.95830918 0.95830918 0.95821256
 0.95603865 0.96038647 0.96043478 0.96043478 0.94502415 0.95613527
 0.96048309 0.962657   0.95386473 0.96043478 0.95386473 0.96710145
 0.93173913 0.93835749 0.94714976 0.93835749 0.93391304 0.93830918
 0.93835749 0.94497585 0.9515942  0.93835749 0.94275362 0.93618357
 0.94719807 0.94502415 0.95381643 0.95381643 0.9494686  0.94729469
 0.94942029 0.94729469 0.93628019 0.94512077 0.94724638 0.94719807
 0.94729469 0.94067633 0.93850242 0.94289855 0.93628019 0.94072464
 0.94294686 0.94507246 0.94280193 0.93845411 0.94507246 0.94294686
 0.94299517 0.94729469 0.94512077 0.94729469 0.94729469 0.94507246
 0.94512077 0.9494686  0.94502415 0.9494686  0.94289855 0.94294686
 0.96048309 0.96917874 0.96038647 0.96478261 0.96478261 0.95826087
 0.96043478 0.9626087  0.962657   0.96922705 0.96478261 0.96256039
 0.95821256 0.96483092 0.9626087  0.9647343  0.96917874 0.96270531
 0.96695652 0.9626087  0.96478261 0.962657   0.96700483 0.96917874
 0.96043478 0.9626087  0.95826087 0.96478261 0.95830918 0.96043478
 0.9626087  0.96705314 0.95816425 0.96922705 0.96922705 0.96478261
 0.95830918 0.96043478 0.96705314 0.96478261 0.95830918 0.96700483
 0.962657   0.96483092 0.95826087 0.96048309 0.95821256 0.96487923
 0.96033816 0.962657   0.96048309 0.95821256 0.95599034 0.96483092
 0.96922705 0.96695652 0.96038647 0.96705314 0.96043478 0.96043478
 0.96478261 0.96700483 0.96700483 0.96700483 0.96695652 0.9626087
 0.96700483 0.9626087  0.96043478 0.95826087 0.96043478 0.96256039
 0.95381643 0.96483092 0.95603865 0.9626087  0.95386473 0.9626087
 0.9626087  0.96256039 0.95594203 0.96038647 0.95826087 0.96483092
 0.95603865 0.96038647 0.96478261 0.9626087  0.96487923 0.96043478
 0.95826087 0.95826087 0.96043478 0.96695652 0.96256039 0.96705314
 0.92951691 0.9384058  0.94714976 0.94072464 0.94062802 0.93618357
 0.93618357 0.93173913 0.93183575 0.94937198 0.94275362 0.94285024
 0.94057971 0.95164251 0.9494686  0.94942029 0.92743961 0.94512077
 0.95376812 0.94492754 0.94062802 0.95164251 0.94507246 0.94942029
 0.94512077 0.94072464 0.94512077 0.94072464 0.9363285  0.94724638
 0.94729469 0.94507246 0.94502415 0.94072464 0.94077295 0.94072464
 0.94072464 0.93845411 0.94512077 0.94729469 0.94942029 0.94512077
 0.94724638 0.94729469 0.93855072 0.94285024 0.94507246 0.94507246
 0.95816425 0.95816425 0.95821256 0.95826087 0.96705314 0.9647343
 0.96917874 0.9626087  0.95154589 0.96483092 0.96478261 0.96256039
 0.9605314  0.96038647 0.96033816 0.9647343  0.96043478 0.962657
 0.9626087  0.96913043 0.96700483 0.96478261 0.96038647 0.96038647
 0.96043478 0.95599034 0.9626087  0.9626087  0.96913043 0.96483092
 0.96483092 0.96487923 0.95608696 0.9626087  0.962657   0.96483092
 0.95164251 0.96043478 0.96038647 0.96700483 0.96483092 0.962657
 0.96256039 0.96700483 0.962657   0.96483092 0.95826087 0.95830918
 0.94922705 0.9626087  0.9626087  0.96483092 0.95816425 0.96695652
 0.96487923 0.97140097 0.96038647 0.9626087  0.96695652 0.9626087
 0.95821256 0.96695652 0.9626087  0.96700483 0.96705314 0.96695652
 0.95826087 0.96700483 0.962657   0.9626087  0.9626087  0.96913043
 0.96256039 0.96048309 0.95381643 0.95821256 0.95603865 0.96705314
 0.96492754 0.96917874 0.962657   0.96478261 0.96256039 0.96922705
 0.94516908 0.95599034 0.9626087  0.96048309 0.96270531 0.95821256
 0.96700483 0.962657   0.95816425 0.96487923 0.962657   0.96483092
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan]
  warnings.warn(

0.9714009661835747
{'bootstrap': True, 'criterion': 'log_loss', 'max_depth': None, 'max_features': 0.2, 'max_samples': 0.75, 'n_estimators': 120}

In [102]:
params = {
'n_estimators' : n_estimators,
'max_features' : max_features,
'max_depth' : max_depth,
'max_samples' : max_samples,
'bootstrap': bootstrap,
'criterion' : criterion,
}
print(params)

{'n_estimators': [20, 60, 100, 120], 'max_features': [0.2, 0.6, 1.0, None], 'max_depth': [2, 8, None], 'max_samples': [0.5, 0.75, 1.0], 'bootstrap': [True, False], 'criterion': ['gini', 'entropy', 'log_loss']}

In [113]:
print(search.best_score_)
print(search.best_params_)

0.9714009661835747
{'bootstrap': True, 'criterion': 'log_loss', 'max_depth': None, 'max_features': 0.2, 'max_samples': 0.75, 'n_estimators': 120}